### PR TITLE
Add keystone v3

### PR DESCRIPTION
**Pull request by perrito666**
Improved over @mhilton patch to add a few missing fields and sensible defaults.
Added live testing for V3 keystone
Added domain support for env variables.

### CODE REVIEW

**Comment by dimitern** [comment]
A few places lack doc comments for exported types/funcs, but otherwise LGTM.

**Comment by dimitern** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by dimitern** [comment]
$$merge$$

**Pull request merged**
